version: '3.1'

services:
  weather-db:
    image: postgres
    restart: always
    container_name: weather
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: weather-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
